### ISSUE TITLE
AttributeError after upgrade to 0.2.2

### ISSUE THREAD

**Issue by spvkgn** [np1/mps-youtube#214]
Previous version works well. With latest I get this error
```
~ $ mpsyt --debug

mpsyt version  : 0.2.2 
   notes       : released 14 Feb 2015
pafy version   : 0.3.72
Python version : 2.7.3 (default, Dec 18 2014, 19:03:52) 
[GCC 4.6.3]
Processor      : i686
Machine type   : i686
Architecture   : 32bit, ELF
Platform       : Linux-3.2.0-69-generic-pae-i686-with-LinuxMint-13-maya
sys.stdout.enc : UTF-8
default enc    : ascii
Config dir     : /home/pavel/.config/mps-youtube
env:TERM       : xterm-256color
env:SHELL      : /bin/bash
env:LANG       : ru_RU.UTF-8
--




Enter /search-term to search or [h]elp
Traceback (most recent call last):
  File "/usr/local/bin/mpsyt", line 11, in <module>
    sys.exit(main.main())
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 4309, in main
    open_from_file()
  File "/usr/local/lib/python2.7/dist-packages/mps_youtube/main.py", line 1301, in open_from_file
    g.userpl = pickle.load(plf)
AttributeError: 'module' object has no attribute 'Playlist'

~ $ cat /tmp/mpsyt.log
DEBUG:root:Read history file
DEBUG:root:transcoding config file exists
DEBUG:root:mpv version 0.5.4 detected
DEBUG:root:searching path for ffmpeg
DEBUG:root:found at /home/pavel/apps/bin/ffmpeg
```

**Comment by np1** [comment]
I think this is related to https://github.com/np1/mps-youtube/pull/187#issuecomment-69690919 (https://github.com/np1/mps-youtube/commit/84e3fec61a8c2f768d48e6eacc4708ad4d9617e0) but I don't get why it affects some (or one) and not others. Maybe it's to do with the version of Python being used (2.7.3).

**Comment by np1** [comment]
@spvkgn I have reverted the suspect commit in issue214 branch.

You can install it with pip to test whether it helps:

`sudo pip install https://github.com/np1/mps-youtube/archive/issue214.zip --upgrade`

**Comment by ids1024** [comment]
@np1 Could it be due to an old playlist?  All the code was originally in the script `pmsyt`, which was `__main__`, so that is how it was referenced in a playlist created by an old version.

**Comment by spvkgn** [comment]
@np1 I have tried, it works with reverted commit
```
./mpsyt --debug

mpsyt version  : 0.2.2 
   notes       : released 14 Feb 2015
pafy version   : 0.3.72
Python version : 2.7.3 (default, Dec 18 2014, 19:03:52) 
[GCC 4.6.3]
Processor      : i686
Machine type   : i686
Architecture   : 32bit, ELF
Platform       : Linux-3.2.0-69-generic-pae-i686-with-LinuxMint-13-maya
sys.stdout.enc : UTF-8
default enc    : ascii
Config dir     : /home/pavel/.config/mps-youtube
env:TERM       : xterm-256color
env:SHELL      : /bin/bash
env:LANG       : ru_RU.UTF-8
--




Enter /search-term to search or [h]elp
> 
```

**Comment by ids1024** [comment]
A little research suggests that my explanation above is correct.

@np1 You should add a comment explaining this in the code and release a bug fix release.

**Comment by np1** [comment]
Thanks for finding the cause of this @ids1024 

It would affect those that have an old (pre v0.01.46) playlist file that have never saved / modified any playlists since then.

I have added a small fix to catch the `AttributeError` and rewrite the playlist file which should allow us to eventually get rid of the `__main__` import.

I will push v0.2.3 very soon.

**Comment by np1** [comment]
Resolved in v0.2.3

branch `issue214` deleted
